Biomedicina/Models/Producto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Biomedicina.Models
{
    public class Producto
    {

        public int Id { get; set; }

        public string Nombre { get; set; }

        public int Id_categoria { get; set; }

        public string Nombre_categoria { get; set; }

        public string Nombre_empresa { get; set; }

        public string Modelo { get; set; }

        public string Descripcion { get; set; }

        public string Espec_tecnica { get; set; }

        public string Url_ficha_tecnica { get; set; }

        public string Imagen_url { get; set; }

        public string Capacidad { get; set; }

        public string Dimension { get; set; }

        public string Temporizador { get; set; }

        public string Temperatura { get; set; }

        public string Dimension_tanque { get; set; }

        public string Potencia { get; set; }

        public string Energia { get; set; }

    }
}

Biomedicina/Models/ProductoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Biomedicina.Models
{
    public class ProductoViewModel
    {

        public List<Producto> lstProducto { get; set; }

        public List<Empresa> lstEmpresa { get; set; }

        public List<Cotizacion> lstCotizacion { get; set; }

        /*Cotizacion*/
        public int IdCotizacion { get; set; }

        public int IdProducto { get; set; }

        public int IdUsuario { get; set; }

        public string Mensaje { get; set; }

        public Cliente Cliente { get; set; }

        public Login Login { get; set; }
    }
}

Biomedicina/Controllers/ProductosController.cs
using Biomedicina.Models;
using Biomedicina.Repository.Biomedicina;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Transactions;

namespace Biomedicina.Controllers
{
    public class ProductosController : Controller
    {

        ProductoViewModel objProductoViewModel = new ProductoViewModel();
        BusquedaAccess objBusqueda = new BusquedaAccess();
        RegistroAccess objRegistro = new RegistroAccess();


        // GET: Productos
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Resultados(Producto objProducto)
        {

            List<Producto> lista_producto;
            List<Empresa> lista_empresa;


            lista_producto = objBusqueda.BuscarProductoxCategoria(objProducto);
            lista_empresa = objBusqueda.ListarEmpresa();

            objProductoViewModel.lstProducto = lista_producto;
            objProductoViewModel.lstEmpresa = lista_empresa;

            return View(objProductoViewModel);

        }

        public ActionResult FiltrarXEmpresa(string idEmpresa,string idCategoria)
        {

            List<Producto> lista_producto = new List<Producto>();

            List<Producto> lista_producto_acumulado = new List<Producto>();

            string[] arr = idEmpresa.Split(',');

            foreach (var id in arr) {

                lista_producto = objBusqueda.FiltrarProductoXEmpresa(Convert.ToInt32(id), Convert.ToInt32(idCategoria));

                lista_producto_acumulado.AddRange(lista_producto);

                objProductoViewModel.lstProducto = lista_producto_acumulado;
            }

            return PartialView("~/Views/Productos/_Resultados.cshtml", objProductoViewModel);

        }

        [HttpPost]
        public ActionResult OpenModalCotizacion(string idProducto) {

            try
            {

                List<Producto> lista_producto;
                Cotizacion objCotizacion = new Cotizacion();

                lista_producto = objBusqueda.BuscarProductoxId(Convert.ToInt32(idProducto));

                objProductoViewModel.lstProducto = lista_producto;
                ViewBag.lstProductoSelect = lista_producto;

                return PartialView("~/Views/Productos/_ModalCotizacion.cshtml", objProductoViewModel);

            }
            catch (Exception ex) 
            {
                return View("~/Views/Shared/Error.cshtml");

            }

        }

        [HttpPost]
        public ActionResult RegistrarCotizacion(ProductoViewModel objProducto)
        {

            String mensaje = "";
            String resultado = "";
            String valid = "";
            String fecha = "";
            String accion = "";
            List<Producto> lista_producto;


            //using (TransactionScope transaccion = new TransactionScope())
            //{

                try
                {
                    if (ModelState.IsValid)
                    {



                        /****Logica para grabar la cotizacion****/

                        mensaje=objRegistro.RegistrarCotizacion(objProducto);


                    if (mensaje.Equals("OK"))
                    {
                        ViewBag.Message = "Se envio la cotizacion";


                    }
                    else {

                        ViewBag.Message = mensaje;

                    }


                    lista_producto = objBusqueda.BuscarProductoxId(Convert.ToInt32(objProducto.IdProducto));

                        objProductoViewModel.lstProducto = lista_producto;

                        mensaje = "Se grabo correctamente la información.";

                        ModelState.Clear();
                        //transaccion.Complete();

                        resultado = "OK";
                        return PartialView("~/Views/Productos/_FormCotizacion.cshtml", objProductoViewModel);

                    }

                    lista_producto = objBusqueda.BuscarProductoxId(Convert.ToInt32(objProducto.IdProducto));

                    objProductoViewModel.lstProducto = lista_producto;

                    return PartialView("~/Views/Productos/_FormCotizacion.cshtml", objProductoViewModel);


                }

                catch (Exception ex)
                {
                    //transaccion.Dispose();

                    mensaje = ex.Message;
                    resultado = "ER";
                    return View("~/Views/Shared/Error.cshtml");


                }

            //}
           
        }

        [HttpPost]
        public JsonResult RegistrarCotizacion2(ProductoViewModel objProducto)
        {

            String mensaje = "";
            String resultado = "";
            String valid = "";
            String fecha = "";
            String accion = "";


            using (TransactionScope transaccion = new TransactionScope())
            {

                try
                {
                    
                    mensaje = "Se elimino correctamente la información.";

                    transaccion.Complete();

                    resultado = "OK";

                }
                catch (Exception ex)
                {
                    transaccion.Dispose();

                    mensaje = ex.Message;
                    resultado = "ER";

                }

            }
            return Json(new { contenido = mensaje, indicador = resultado });
        }

        public ActionResult VerDetalleProducto(int idProducto) {


            try
            {

                List<Producto> lista_producto;
                List<Especificacion_tecnica> lita_espec_tecnica;
                Cotizacion objCotizacion = new Cotizacion();

                lista_producto = objBusqueda.BuscarProductoxId(idProducto);

                objProductoViewModel.lstProducto = lista_producto;
                ViewBag.lstProductoSelect = lista_producto;

                return View(objProductoViewModel);

            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml");

            }



        }

    }
}

Biomedicina/Views/Productos/Resultados.cshtml
@model Biomedicina.Models.ProductoViewModel
@{
    ViewBag.Title = "ResultadosProducto";

    var lstProductos = Model.lstProducto;

}

@*<h2>ResultadosProducto</h2>*@

<!-- Inner container -->
<div class="d-flex align-items-start flex-column flex-md-row">

    <!-- Left content -->
    <div class="w-100 overflow-auto order-2 order-md-1" id="divResultadosProductos">

        @Html.Partial("~/Views/Productos/_Resultados.cshtml", Model)


    </div>
    <!-- /left content -->
    <!-- Right sidebar component -->
    <div class="sidebar sidebar-light bg-transparent sidebar-component sidebar-component-right border-0 shadow-0 order-1 order-md-2 sidebar-expand-md">

        <!-- Sidebar content -->
        <div class="sidebar-content">

            @Html.Partial("~/Views/Productos/_FormFiltro.cshtml", Model)

        </div>
        <!-- /sidebar content -->

    </div>
    <!-- /right sidebar component -->

</div>
<!-- /inner container -->

Biomedicina/Views/Productos/_FormCotizacion.cshtml
@model Biomedicina.Models.ProductoViewModel
@{

    var lstProductos = Model.lstProducto;
    var lstProductoSelect = ViewBag.lstProductoSelect;

}
<div class="form-group row">
    <label class="col-form-label col-sm-3">Modelo :</label>
    <div class="col-sm-9">
        <div class="form-control-plaintext" name="Modelo" id="Modelo">@lstProductos.FirstOrDefault().Modelo</div>
    </div>
</div>

<div class="form-group row">
    <label class="col-form-label col-sm-3">Empresa :</label>
    <div class="col-sm-9">
        <div class="form-control-plaintext" name="NombreEmpresa" id="NombreEmpresa">@lstProductos.FirstOrDefault().Nombre_empresa</div>
    </div>
</div>


<div class="form-group row">
    <label class="col-form-label col-sm-3">Mensaje :</label>
    <div class="col-sm-9">
        @Html.TextAreaFor(m => m.Mensaje, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Mensaje, "", new { @class = "validation-invalid-label" })

        @*<textarea name="Mensaje" id="Mensaje" rows="3" cols="3" class="form-control" placeholder="Default textarea"></textarea>*@
    </div>
</div>

@Html.AntiForgeryToken()
@if (ViewBag.Message != null)
{
    <span class="text-success">@ViewBag.Message</span>
}

Biomedicina/Views/Productos/_FormFiltro.cshtml
@model Biomedicina.Models.ProductoViewModel
@{
    ViewBag.Title = "ResultadosProducto";

    var lstProductos = Model.lstProducto;

    var id_categoria = lstProductos.FirstOrDefault().Id_categoria;
    var lstEmpresas = Model.lstEmpresa;

}
<!-- Sidebar content -->
<div class="sidebar-content">
    <!-- Filters -->
    <div class="card">
        <div class="card-header bg-transparent header-elements-inline">
            <span class="text-uppercase font-size-sm font-weight-semibold">Filtrar productos</span>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                </div>
            </div>
        </div>

        <div class="card-body">
                <div class="form-group" id="ItemList">
                    @*<div class="form-group form-group-feedback form-group-feedback-left">
                        <input type="search" class="form-control" placeholder="Search brand">
                        <div class="form-control-feedback">
                            <i class="icon-search4 font-size-base text-muted"></i>
                        </div>
                    </div>*@

                    <div class="overflow-auto" style="max-height: 192px;">

                        @*@for (int i = 0; i < lstEmpresas.Count; i++)
                        {
                            <div class="form-check" id="@lstEmpresas[i].Id">
                                <label class="form-check-label">
                                    <input type="checkbox" name="filtroEmpresas" class="form-input-styled" onclick="return f_filtrar_x_empresa(@lstEmpresas[i].Id);" data-fouc>
                                    @lstEmpresas[i].Razon_social
                                </label>
                            </div>

                        }*@


                        @foreach (var item in lstEmpresas)
                        {

                            <div class="form-check">
                                <label class="form-check-label" for="Check_@item.Id">
                                    <input type="checkbox" name="filtroEmpresas" id="Check_@item.Id" class="form-input-styled" onclick="return f_filtrar_x_empresa(@id_categoria);" data-fouc>
                                    @item.Razon_social
                                </label>
                            </div>

                        }

                    </div>
                </div>

                @*<button type="submit" class="btn bg-blue btn-block">Filtrar</button>*@
        </div>
    </div>
    <!-- /filters -->

</div>
<!-- /sidebar content -->

Biomedicina/Views/Productos/_ModalCotizacion.cshtml
    @model Biomedicina.Models.ProductoViewModel
@{

    var lstProductos = Model.lstProducto;
    var lstProductoSelect = ViewBag.lstProductoSelect;

}

@using (Ajax.BeginForm("RegistrarCotizacion", "Productos", new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "frmEmp" }))
{
    <!-- Horizontal form modal -->
    <div id="modal_form_horizontal" class="modal fade" tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Solicitar Cotización</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>




                @Html.HiddenFor(m => m.IdProducto, new { id = "", Value = lstProductos.FirstOrDefault().Id })
                @Html.HiddenFor(m => m.IdUsuario, new { id = "", Value = "1" })


                <div class="modal-body" id="frmEmp">

                    @Html.Partial("~/Views/Productos/_FormCotizacion.cshtml")

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-link" data-dismiss="modal">Cerrar</button>
                    <button type="submit" id="btnRegistrarCotizacion" class="btn bg-primary">Enviar cotización</button>
                </div>

             



                @*<form class="form-horizontal" id="RegistrarCotizacionForm">
                        <div class="modal-body">
                            <div class="form-group row">
                                <label class="col-form-label col-sm-3">Modelo</label>
                                <div class="col-sm-9">
                                    <div class="form-control-plaintext" name="Modelo" id="Modelo">@lstProductos.FirstOrDefault().Modelo</div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-form-label col-sm-3">Empresa</label>
                                <div class="col-sm-9">
                                    <div class="form-control-plaintext" name="NombreEmpresa" id="NombreEmpresa">@lstProductos.FirstOrDefault().Nombre_empresa</div>
                                </div>
                            </div>


                            <div class="form-group row">
                                <label class="col-form-label col-sm-3">Mensaje :</label>
                                <div class="col-sm-9">

                                    <textarea name="Mensaje" id="Mensaje" rows="3" cols="3" class="form-control" placeholder="Default textarea"></textarea>
                                </div>
                            </div>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-link" data-dismiss="modal">Cerrar</button>
                            <button type="submit" id="btnRegistrarCotizacion" class="btn bg-primary">Enviar cotización</button>
                        </div>
                    </form>*@


            </div>
        </div>
    </div>
    <!-- /horizontal form modal -->
}

Biomedicina/Views/Productos/_Resultados.cshtml
@model Biomedicina.Models.ProductoViewModel
@{

    var lstProductos = Model.lstProducto;

}

<!-- Grid -->
<div class="row">

    @for (int i = 0; i < lstProductos.Count; i++)
    {

        <div class="col-xl-3 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <div class="card-img-actions">
                        <a href="@lstProductos[i].Imagen_url" data-popup="lightbox">
                            <img src="@lstProductos[i].Imagen_url" class="card-img" width="96" alt="">
                            @*<div class="card-img-actions-overlay card-img">

                                    <a href="~/Content/global_assets/images/placeholders/placeholder.jpg" class="btn btn-outline bg-white text-white border-white border-2 btn-icon rounded-round" data-popup="lightbox" rel="group">
                                        <i class="icon-plus3"></i>
                                    </a>

                                    <a href="#" class="btn btn-outline bg-white text-white border-white border-2 btn-icon rounded-round ml-2">
                                        <i class="icon-link"></i>
                                    </a>
                                </div>*@
                            <span class="card-img-actions-overlay card-img">
                                <i class="icon-plus3 icon-2x"></i>
                            </span>
                        </a>
                    </div>
                </div>

                <div class="card-body bg-light text-center">
                    <div class="mb-2">
                        <h6 class="font-weight-semibold mb-0">
                            <a href="#" class="text-default">@lstProductos[i].Nombre</a>
                        </h6>

                        <a href="#" class="text-muted">@lstProductos[i].Nombre_categoria</a>
                        <a href="#" class="text-muted">@lstProductos[i].Nombre_empresa</a>

                    </div>

                    @*<h3 class="mb-0 font-weight-semibold">$49.99</h3>*@

                    @*<div>
                            <i class="icon-star-full2 font-size-base text-warning-300"></i>
                            <i class="icon-star-full2 font-size-base text-warning-300"></i>
                            <i class="icon-star-full2 font-size-base text-warning-300"></i>
                            <i class="icon-star-full2 font-size-base text-warning-300"></i>
                            <i class="icon-star-full2 font-size-base text-warning-300"></i>
                        </div>

                        <div class="text-muted mb-3">85 reviews</div>*@

                    @*<button type="button" class="btn bg-teal-400" data-toggle="modal" data-target="#modal_form_horizontal" onclick="openModalCotizacion(@lstProductos[i].Id)"><i class="icon-cart-add mr-2"></i> Solicitar cotización</button>*@
                    @*<button type="button" class="btn bg-teal-400" onclick="openModalCotizacion(@lstProductos[i].Id)" data-target="#modal_form_horizontal"><i class="icon-cart-add mr-2"></i> Solicitar cotización</button>*@
                    @*<button type="button" class="btn bg-teal-400" onclick="@Url.Action("VerDetalleProducto", "Productos",new { idProducto = lstProductos[i].Id })"><i class="icon-cart-add mr-2"></i> Ver detalle</button>*@
                    <a class="btn bg-teal-400" href="@Url.Action("VerDetalleProducto", "Productos",new { idProducto = lstProductos[i].Id })">
                        Ver detalle
                    </a>


                </div>
            </div>
        </div>



    }
    @*<div class="col-xl-3 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <div class="card-img-actions">
                        <a href="~/Content/global_assets/images/placeholders/placeholder.jpg" data-popup="lightbox">
                            <img src="~/Content/global_assets/images/placeholders/placeholder.jpg" class="card-img" width="96" alt="">
                            <span class="card-img-actions-overlay card-img">
                                <i class="icon-plus3 icon-2x"></i>
                            </span>
                        </a>
                    </div>
                </div>

                <div class="card-body bg-light text-center">
                    <div class="mb-2">
                        <h6 class="font-weight-semibold mb-0">
                            <a href="#" class="text-default">Fathom Backpack</a>
                        </h6>

                        <a href="#" class="text-muted">Men's Accessories</a>
                    </div>

                    <h3 class="mb-0 font-weight-semibold">$49.99</h3>

                    <div>
                        <i class="icon-star-full2 font-size-base text-warning-300"></i>
                        <i class="icon-star-full2 font-size-base text-warning-300"></i>
                        <i class="icon-star-full2 font-size-base text-warning-300"></i>
                        <i class="icon-star-full2 font-size-base text-warning-300"></i>
                        <i class="icon-star-full2 font-size-base text-warning-300"></i>
                    </div>

                    <div class="text-muted mb-3">85 reviews</div>

                    <button type="button" class="btn bg-teal-400"><i class="icon-cart-add mr-2"></i> Add to cart</button>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <div class="card-img-actions">
                        <a href="~/Content/global_assets/images/placeholders/placeholder.jpg" data-popup="lightbox">
                            <img src="~/Content/global_assets/images/placeholders/placeholder.jpg" class="card-img" width="96" alt="">
                            <span class="card-img-actions-overlay card-img">
                                <i class="icon-plus3 icon-2x"></i>
                            </span>
                        </a>
                    </div>
                </div>

                <div class="card-body bg-light text-center">
                    <div class="mb-2">
                        <h6 class="font-weight-semibold mb-0">
                            <a href="#" class="text-default mb-0">Mystery Air Long Sleeve T Shirt</a>
                        </h6>

                        <a href="#" class="text-muted">Men's Fashion</a>
                    </div>

                    <h3 class="mb-0 font-weight-semibold">$25.99</h3>

                    <div>
                        <i class="icon-star-full2 font-size-base text-warning-300"></i>
                        <i class="icon-star-full2 font-size-base text-warning-300"></i>
                        <i class="icon-star-full2 font-size-base text-warning-300"></i>
                        <i class="icon-star-full2 font-size-base text-warning-300"></i>
                        <i class="icon-star-half font-size-base text-warning-300"></i>
                    </div>

                    <div class="text-muted mb-3">34 reviews</div>

                    <button type="button" class="btn bg-teal-400"><i class="icon-cart-add mr-2"></i> Add to cart</button>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <div class="card-img-actions">
                        <a href="~/Content/global_assets/images/placeholders/placeholder.jpg" data-popup="lightbox">
                            <img src="~/Content/global_assets/images/placeholders/placeholder.jpg" class="card-img" width="96" alt="">
                            <span class="card-img-actions-overlay card-img">
                                <i class="icon-plus3 icon-2x"></i>
                            </span>
                        </a>
                    </div>
                </div>

                <div class="card-body bg-light text-center">
                    <div class="mb-2">
                        <h6 class="font-weight-semibold mb-0">
                            <a href="#" class="text-default mb-0">Women’s Prospect Backpack</a>
                        </h6>

                        <a href="#" class="text-muted">Women's Accessories</a>
                    </div>

                    <h3 class="mb-0 font-weight-semibold">$63.99</h3>

                    <div>
                        <i class="icon-star-full2 font-size-base text-warning-300"></i>
                        <i class="icon-star-full2 font-size-base text-warning-300"></i>
                        <i class="icon-star-full2 font-size-base text-warning-300"></i>
                        <i class="icon-star-full2 font-size-base text-warning-300"></i>
                        <i class="icon-star-empty3 font-size-base text-warning-300"></i>
                    </div>

                    <div class="text-muted mb-3">63 reviews</div>

                    <button type="button" class="btn bg-teal-400"><i class="icon-cart-add mr-2"></i> Add to cart</button>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <div class="card-img-actions">
                        <a href="~/Content/global_assets/images/placeholders/placeholder.jpg" data-popup="lightbox">
                            <img src="~/Content/global_assets/images/placeholders/placeholder.jpg" class="card-img" width="96" alt="">
                            <span class="card-img-actions-overlay card-img">
                                <i class="icon-plus3 icon-2x"></i>
                            </span>
                        </a>
                    </div>
                </div>

                <div class="card-body bg-light text-center">
                    <div class="mb-2">
                        <h6 class="font-weight-semibold mb-0">
                            <a href="#" class="text-default mb-0">Overlook Short Sleeve T Shirt</a>
                        </h6>

                        <a href="#" class="text-muted">Men's Fashion</a>
                    </div>

                    <h3 class="mb-0 font-weight-semibold">$57.99</h3>

                    <div>
                        <i class="icon-star-full2 font-size-base text-warning-300"></i>
                        <i class="icon-star-full2 font-size-base text-warning-300"></i>
                        <i class="icon-star-full2 font-size-base text-warning-300"></i>
                        <i class="icon-star-full2 font-size-base text-warning-300"></i>
                        <i class="icon-star-full2 font-size-base text-warning-300"></i>
                    </div>

                    <div class="text-muted mb-3">74 reviews</div>

                    <button type="button" class="btn bg-teal-400"><i class="icon-cart-add mr-2"></i> Add to cart</button>
                </div>
            </div>
        </div>*@

</div>


<!-- /grid -->
<!-- Pagination -->
<div class="d-flex justify-content-center pt-3 mb-3">
    <ul class="pagination">
        <li class="page-item"><a href="#" class="page-link"><i class="icon-arrow-left12"></i></a></li>
        <li class="page-item active"><a href="#" class="page-link">1</a></li>
        <li class="page-item"><a href="#" class="page-link">2</a></li>
        <li class="page-item"><a href="#" class="page-link">3</a></li>
        <li class="page-item"><a href="#" class="page-link">4</a></li>
        <li class="page-item"><a href="#" class="page-link">5</a></li>
        <li class="page-item"><a href="#" class="page-link"><i class="icon-arrow-right13"></i></a></li>
    </ul>
</div>
<!-- /pagination -->
@*<div id="cotizacionContainer">

        @Html.Partial("~/Views/Productos/_ModalCotizacion.cshtml")

    </div>*@